version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: elite_db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .data:/var/lib/mysql

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
